const errorsType = {
    ROUTING_ERROR: 1,
    INVALID_TYPE: 2,
    DATABASE_ERROR: 3,
    AUTHENTICATION_ERROR: 4,
    PRODUCTS_ERROR: 5,
    USER_ERROR: 6,
    CART_ERROR: 7,
    REGISTER_ERROR: 8,
    LOGIN_ERROR: 9,
    DELOGIN_ERROR: 10,
    NOPERMISSIONS_ERROR: 11,
    RENDER_ERROR: 12,
    TICKET_ERROR: 13,
}

export default errorsType;